baseurl = "http://englianhu.github.io"
languageCode = "en-us"
title = "®γσ, ξηg Lιαη Ημ"
paginate = 8
theme = "hugo-theme-timeline"
[params]
    description = "数学中国：ξconometrics量化圈共识加油！"
    email = "englianhu@gmail.com"
[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"
    